# data_gen/regions.toml
#
# Copyright (C) 2025 Michael G
# Licensed under MIT. See LICENSE

[new_bark_town_players_house_1f]
exits = [
    "new_bark_town_players_house_2f",
    "new_bark_town"
]
header = "new_bark_town_players_house_1f"

[new_bark_town]
exits = [
    "route_29",
    "new_bark_town_players_house_1f",
    "new_bark_town_elms_lab",
    "new_bark_town_neighbor_house"
]
header = "new_bark_town"

[new_bark_town_elms_lab]
exits = ["new_bark_town"]
header = "new_bark_town_elms_lab"
locs = [
    "new_bark_town_elms_lab_master_ball", 
    "new_bark_town_elms_lab_potion"
]

[route_29]
exits = [
    "new_bark_town",
    "cherrygrove_city",
    "route_46" # Ledge logic handles one-way in rules.toml
]
header = "route_29"
locs = [
    "route_29_potion"
]
