# data_gen/rom_interface.toml
#
# Copyright (C) 2025 James Petersen <m@jamespetersen.ca>
# Licensed under MIT. See LICENSE

loc_table.base = 0
loc_table.overworld = 1
loc_table.hidden = 2
loc_table.once = 3

item_clas.bagitem = 0
item_clas.multibagitem0 = 1
item_clas.multibagitem1 = 2
item_clas.multibagitem2 = 3
item_clas.specialbagitem = 4
item_clas.poketchapp = 5
item_clas.badge = 6
item_clas.accessory = 7
item_clas.special = 0xE

# HM MAPPING (HGSS)
hm.cut = "hm01"
hm.fly = "hm02"
hm.surf = "hm03"
hm.strength = "hm04"
hm.whirlpool = "hm05" 
hm.rock_smash = "hm06"
hm.waterfall = "hm07"
hm.rock_climb = "hm08"# Flash is TM70 in both, but a Field Move in HGSS
hm.flash = "tm70"     

# BADGE MAPPING (Johto)
hm_badge.cut = "hive_badge"       # Cut requires Hive Badge
hm_badge.fly = "storm_badge"      # Fly requires Storm Badge
hm_badge.surf = "fog_badge"       # Surf requires Fog Badge
hm_badge.strength = "plain_badge" # Strength requires Plain Badge
hm_badge.whirlpool = "glacier_badge" # Whirlpool requires Glacier Badge
hm_badge.rock_smash = "zephyr_badge" # Rock Smash requires Zephy Badge
hm_badge.waterfall = "rising_badge"  # Waterfall requires Rising Badge
hm_badge.rock_climb = "earth_badge"  # Rock Climb requires Earth Badge (Kanto)
req_items = ["dowsingmachine"]

item_group.items = "Items"
item_group.key_items = "Key Items"
item_group.badges = "Badges"
item_group.berries = "Berries"
item_group.pokedex = "Pok√©dex"
item_group.balls = "Balls"
item_group.tmhms = "TMs and HMs"
item_group.medicine = "Medicine"
item_group.mail = "Mail"
item_group.battle_items = "Battle Items"
